# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDRtomPu60HJNS7wTODFAcRXKYJeUWm3

KNN (Classifier and regressor)
"""

from sklearn.datasets import load_iris
import pandas as pd


iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target
df.head()

df.describe()

x=df.drop('target', axis=1)
y=df['target']

#already normalised
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

acc = []
for k in range(1,22):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    acc.append(knn.score(x_test,y_test))

plt.plot(range(1,22),acc)
plt.xlabel('k')
plt.ylabel('accuracy')
plt.grid()
plt.show()

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
knn.predict([[5.1,3.5,1.4,0.5]])