# -*- coding: utf-8 -*-
"""Random Forest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltojoaOQvxXMf9h9NzGF82YfGLCQ7UeI
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.get_dataset_names()

healthexp = sns.load_dataset('healthexp')
healthexp.head()

healthexp.info()

healthexp =pd.get_dummies(healthexp)
healthexp.head()

x= healthexp.drop('Life_Expectancy', axis=1)
y= healthexp['Life_Expectancy']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestRegressor
model =RandomForestRegressor()
model.fit(x_train, y_train)

model.predict(x_test)

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
r2_score(y_test, model.predict(x_test))

mean_squared_error(y_test, model.predict(x_test))

mean_absolute_error(y_test, model.predict(x_test))