# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qC_pAjCFMay5qRdZwK07Rk380rLuNW15

**Support vector machine**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets

iris=datasets.load_iris()
df=pd.DataFrame(iris.data, columns=iris.feature_names)

df['target']=iris.target
df.head()

x=df.drop('target', axis=1)
y=df.target

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2,random_state=1)

plt.scatter(x_train.iloc[:, 2], x_train.iloc[:, 3], c=y_train)
plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm)')

"""not linearly separable, there is some overlap"""

from ast import mod
from sklearn.svm import SVC
model=SVC(kernel='linear' )
model.fit(x_train, y_train)
model.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, model.predict(x_test)))

from ast import mod
from sklearn.svm import SVC
model=SVC(kernel='rbf', gamma=1 )
model.fit(x_train, y_train)
model.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test, model.predict(x_test)))

plt.scatter(x_test.iloc[:, 2], x_test.iloc[:, 3], c=y_test)
plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm)')